services:
  query-agent-db:
    container_name: query-agent-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  query-agent-backend:
    container_name: query-agent-backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - query-agent-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: query-agent-db
    volumes:
      - ./shared_utils:/app/shared_utils
    networks:
      - shared-network

  query-agent-frontend:
    container_name: query-agent-frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8501"
    depends_on:
      - query-agent-backend
    volumes:
      - ./shared_utils:/app/shared_utils
    networks:
      - shared-network

networks:
  shared-network:
    external: true
